### ISSUE TITLE
Template Gallery Review

### ISSUE THREAD

**Issue by delsonting** [adxcgcom/adxcg-gtm-template-simple-pixel#1]
Thanks for submitting this template for the Gallery, here is the feedback from review:

1. [Required] The documentation link is broken, however you can drop this field (rather than fixing the url) if you're planning on linking to the github repo. A link to the github repo will be provided automatically
2. [Recommended] Provide validation on the endpoint field to ensure the url provided by the customer matches the injectscript permission (https://cdn.adxcg.net/*)

Once these are remedied, add a comment to this issue and I'll reverify.

**Comment by adxcgcom** [comment]
thx. done 1 and 2
